services:
  db:
    image: postgres
    container_name: customer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - customer_db:/var/lib/postgresql/data

volumes:
  customer_db:
